version: "3.8"
services:
  educom:
    container_name: "educom"
    build:
      context: ..
      dockerfile: ./devops/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - educom-postgres-db

  educom-postgres-db:
    container_name: "educom-postgres-db"
    image: postgres:14.0-alpine
    restart: unless-stopped
    volumes:
      - educom_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=educom
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=dbeducom
  
volumes:
  educom_postgres_data: